export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';

export const ADMIN_POST_BLOG_SUCCESS = 'ADMIN_POST_BLOG_SUCCESS';
export const ADMIN_POST_BLOG_FAILED = 'ADMIN_POST_BLOG_FAILED';

export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAILED = 'GET_BLOG_FAILED';

export const CATEGORY_ACTION = 'CATEGORY_ACTION';
export const CATEGORY_ACTION_FAILED = 'CATEGORY_ACTION_FAILED';

export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_FAILURE = 'FETCH_USER_BY_ID_FAILURE';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILED = 'EDIT_CATEGORY_FAILED';

export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILED = 'DELETE_BLOG_FAILED';

export const EDIT_BLOG_SUCCESS = 'EDIT_BLOG_SUCCESS';
export const EDIT_BLOG_FAILED = 'EDIT_BLOG_FAILED';

export const GET_FEATURED_BLOG_SUCCESS = 'GET_FEATURED_BLOG_SUCCESS';
export const GET_FEATURED_BLOG_FAILED = 'GET_FEATURED_BLOG_FAILED';

export const GET_PUBLISHED_BLOG_SUCCESS = 'GET_PUBLISHED_BLOG_SUCCESS';
export const GET_PUBLISHED_BLOG_FAILED = 'GET_PUBLISHED_BLOG_FAILED';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED';

export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';
