export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";


export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";


export const ADMIN_POST_BLOG = "ADMIN_POST_BLOG";

export const CATEGORY_ACTION = 'CATEGORY_ACTION';
export const CATEGORY_ACTION_FAILED = 'CATEGORY_ACTION_FAILED';

export const GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
